package:
  name: gasp
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

requirements:
  build:
    - python
    - pip

  run:
    - python
    - nifty =1.0.9
    - vigra
    - affogato =0.2.2

test:
  requires:
    - pytest
  run:
    - pytest tests/

about:
  home: https://github.com/abailoni/GASP
  license: MIT
